name: Build and deploy Node.js app to Azure Web App - utanzu-nextjs-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js with Yarn
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: yarn

      - name: Cache Node Modules and Next.js Build Cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .next/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Generate Prisma Client
        run: yarn prisma generate

      - name: Build Next.js App
        run: yarn build

      - name: Prepare Deployment Artifact
        run: |
          mkdir deploy
          cp -R .next package.json yarn.lock public deploy/
          cp -R node_modules deploy/
          cp -R prisma deploy/

      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: deploy/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      contents: read

    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app
          path: deploy/

      - name: Install Dependencies on Server
        run: |
          cd deploy
          yarn install --production --frozen-lockfile

      - name: Apply Database Migrations (Prisma)
        run: |
          cd deploy
          yarn prisma migrate deploy

      - name: Deploy to Azure Web App using Publish Profile
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "utanzu-nextjs-app"
          slot-name: "Production"
          package: deploy/
          publish-profile: ${{ secrets.APP_PUBLISH_PROFILE }}

      - name: Health Check After Deployment
        run: |
          sleep 5
          for i in {1..5}; do
            curl -f https://${{ secrets.AZURE_APP_URL }}/api/health && break || sleep 5;
          done
          echo "Health check failed"
