name: Build and deploy Node.js app to Azure Web App - utanzu-nextjs-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version and cache dependencies
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: yarn

      - name: Cache Node Modules and Next.js Build Cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .next/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies (if not cached)
        run: yarn install --frozen-lockfile
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Build Next.js App with Incremental Cache
        run: yarn build

      - name: Generate Prisma Client
        run: yarn prisma generate

      - name: Prepare Deployment Artifact
        run: |
          mkdir deploy
          cp -R .next package.json yarn.lock public deploy/
          cp -R node_modules deploy/
          cp -R prisma deploy/ # Include Prisma migrations if needed

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: deploy/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app
          path: deploy/

      - name: Deploy to Azure Web App using Publish Profile
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "utanzu-nextjs-app"
          slot-name: "Production"
          package: deploy/
          publish-profile: ${{ secrets.APP_PUBLISH_PROFILE }}

      - name: Health Check After Deployment
        run: |
          sleep 5
          curl -f https://${{ secrets.AZURE_APP_URL }}/api/health || echo "Health check failed"
